baseurl = "http://www.qp197.com"

copyright = "2016 Designed By"
disqusshortname = "jiejing-tech"
languagecode = "zh-cn"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "杰竞科技"

[[menu.main]]
identifier = "Office"
name = "杰竞科技官方网站"
url = "/"
weight = -120

[params]
author = "Jiejing"
authorlocation = "Chengdu, China"
authorwebsite = "http://www.qp197.com"
bio = "IT software and Full-stack Engineer, Open source enthusiast."

cover = "images/cover_polenord.png"
descriptionTop = "移动、定位、云计算、数据采集、在线支付融合技术为工具的"
descriptionBottom = "最新最全面的汽车配件信息服务平台"
githubName = "ipconfiger"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "vjeantet"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
